fun main() {
    println("=== 仕訳登録ワークフロー デモ ===")
    println("ワークフロー「仕訳登録」を実装しました:")
    println("")
    println("実装内容:")
    println("1. JournalEntryRepository インターフェースとインメモリ実装")
    println("   - save(event): 仕訳イベントを保存")
    println("   - findById(journalId): ID で仕訳イベントを検索")
    println("   - exists(journalId): 仕訳の存在確認")
    println("")
    println("2. JournalEntryRegistration ワークフロー")
    println("   - 仕訳登録コマンドを受け取り、ビジネスルールを適用")
    println("   - 検証成功時は仕訳登録イベントを生成してリポジトリに保存")
    println("   - エラー時は適切なエラー情報を返却")
    println("")
    println("3. ビジネスルール:")
    println("   - 仕訳明細は最低2行必要")
    println("   - 借方合計と貸方合計が一致する必要がある")
    println("")
    println("ファイル構成:")
    println("- src/main/kotlin/effect/JournalEntryRepository.kt")
    println("- src/main/kotlin/workflow/JournalEntryRegistration.kt")
    println("- src/test/kotlin/workflow/JournalEntryRegistrationTest.kt")
}